export const imageGenerationPrompts = [
    "A futuristic cityscape at night with neon lights.",
    "A magical forest with floating islands and glowing plants.",
    "A cyberpunk street with holographic billboards and flying cars.",
    "An underwater city filled with bioluminescent creatures.",
    "A post-apocalyptic wasteland with ruins and overgrown vegetation.",
    "A whimsical steampunk airship soaring through the clouds.",
    "A serene mountain lake with a reflection of the Milky Way.",
    "A bustling market in a Marrakech-like setting with vibrant colors.",
    "A fairytale castle in a lush, green valley.",
    "A retro 80s-style arcade with pixel art characters and games.",
    "A surreal dreamscape with melting clocks and floating objects.",
    "A peaceful Japanese garden with cherry blossoms and a koi pond.",
    "A space station orbiting a distant exoplanet.",
    "A hidden cave with glowing crystals and a mysterious portal.",
    "A celestial event with shooting stars and a comet in the sky.",
    "A mystical wizard's tower on a hill with a spiral staircase.",
    "A Viking longship sailing on a stormy sea.",
    "A vibrant coral reef teeming with marine life.",
    "A haunted mansion on a foggy night with glowing windows.",
    "A futuristic robot factory with assembly line robots.",
    "A wild west town with a dusty street and saloon.",
    "A tropical paradise island with palm trees and clear waters.",
    "A futuristic cyberpunk nightclub with neon dancers.",
    "A Viking warrior battling a mythical creature in a snowy forest.",
    "A medieval alchemist's laboratory with bubbling potions.",
    "A city park in autumn with colorful leaves falling.",
    "A space explorer on an alien planet with strange flora.",
    "A Viking village under the northern lights in winter.",
    "A secret underwater cave with bioluminescent jellyfish.",
    "A high-tech laboratory with holographic displays.",
    "A medieval jousting tournament in a grand arena.",
    "A rainforest waterfall with lush vegetation.",
    "A retro science fiction rocket launching into space.",
    "A hidden pirate treasure on a desert island.",
    "A modern city skyline with futuristic skyscrapers.",
    "A peaceful countryside farm with rolling hills.",
    "A bustling Chinatown market with lanterns and street food.",
    "A robotic uprising in a dystopian city.",
    "A Mayan temple in a dense jungle.",
    "A magical library with floating books and scrolls.",
  ];

  // access these prompts using index, e.g., imageGenerationPrompts[0]
  